# Generated by Django 5.1 on 2025-02-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100000000)),
            ],
        ),
        migrations.AlterField(
            model_name='team_members',
            name='image',
            field=models.CharField(max_length=100000000),
        ),
    ]
