# Generated by Django 5.1 on 2025-02-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_gallery_alter_team_members_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='blerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100000000)),
                ('image', models.CharField(max_length=100000000)),
                ('events_hosted', models.IntegerField()),
                ('active_members', models.IntegerField()),
                ('startups_launched', models.IntegerField()),
            ],
        ),
    ]
